package http1

var (
	defaultContentType = []byte("text/plain; charset=utf-8")
)

var (
	byteSlash            = []byte("/")
	byteSlashSlash       = []byte("//")
	byteSlashDotDot      = []byte("/..")
	byteSlashDotSlash    = []byte("/./")
	byteSlashDotDotSlash = []byte("/../")
	byteCRLF             = []byte("\r\n")
	byteHTTP             = []byte("http")
	byteHTTPS            = []byte("https")
	byteHTTP11           = []byte("HTTP/1.1")
	byteColon            = []byte(":")
	byteColonSlashSlash  = []byte("://")
	byteColonSpace       = []byte(": ")
	byteGMT              = []byte("GMT")
	byteAt               = []byte("@")

	byteResponseContinue = []byte("HTTP/1.1 100 Continue\r\n\r\n")

	byteGet     = []byte(MethodGet)
	byteHead    = []byte(MethodHead)
	bytePost    = []byte(MethodPost)
	bytePut     = []byte(MethodPut)
	byteDelete  = []byte(MethodDelete)
	byteConnect = []byte(MethodConnect)
	byteOptions = []byte(MethodOptions)
	byteTrace   = []byte(MethodTrace)
	bytePatch   = []byte(MethodPatch)

	byteExpect           = []byte(HeaderExpect)
	byteConnection       = []byte(HeaderConnection)
	byteContentLength    = []byte(HeaderContentLength)
	byteContentType      = []byte(HeaderContentType)
	byteDate             = []byte(HeaderDate)
	byteHost             = []byte(HeaderHost)
	byteReferer          = []byte(HeaderReferer)
	byteServer           = []byte(HeaderServer)
	byteTransferEncoding = []byte(HeaderTransferEncoding)
	byteContentEncoding  = []byte(HeaderContentEncoding)
	byteAcceptEncoding   = []byte(HeaderAcceptEncoding)
	byteUserAgent        = []byte(HeaderUserAgent)
	byteCookie           = []byte(HeaderCookie)
	byteSetCookie        = []byte(HeaderSetCookie)
	byteLocation         = []byte(HeaderLocation)
	byteIfModifiedSince  = []byte(HeaderIfModifiedSince)
	byteLastModified     = []byte(HeaderLastModified)
	byteAcceptRanges     = []byte(HeaderAcceptRanges)
	byteRange            = []byte(HeaderRange)
	byteContentRange     = []byte(HeaderContentRange)
	byteAuthorization    = []byte(HeaderAuthorization)

	byteCookieExpires         = []byte("expires")
	byteCookieDomain          = []byte("domain")
	byteCookiePath            = []byte("path")
	byteCookieHTTPOnly        = []byte("HttpOnly")
	byteCookieSecure          = []byte("secure")
	byteCookieMaxAge          = []byte("max-age")
	byteCookieSameSite        = []byte("SameSite")
	byteCookieSameSiteLax     = []byte("Lax")
	byteCookieSameSitebyteict = []byte("byteict")
	byteCookieSameSiteNone    = []byte("None")

	byteClose               = []byte("close")
	byteGzip                = []byte("gzip")
	byteDeflate             = []byte("deflate")
	byteKeepAlive           = []byte("keep-alive")
	byteUpgrade             = []byte("Upgrade")
	byteChunked             = []byte("chunked")
	byteIdentity            = []byte("identity")
	byte100Continue         = []byte("100-continue")
	bytePostArgsContentType = []byte("application/x-www-form-urlencoded")
	byteMultipartFormData   = []byte("multipart/form-data")
	byteBoundary            = []byte("boundary")
	byteBytes               = []byte("bytes")
	byteTextSlash           = []byte("text/")
	byteApplicationSlash    = []byte("application/")
	byteBasicSpace          = []byte("Basic ")
)
